version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ncs_postgres
    restart: always
    environment:
      POSTGRES_USER: ncs_user
      POSTGRES_PASSWORD: ncs_password
      POSTGRES_DB: ncs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: